2025-03-28 14:51:20,563 : INFO : root : Loading config.
2025-03-28 14:51:20,566 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-28 14:51:20,566 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\homebrew\Desktop\thing_pinball\config\config.yaml
2025-03-28 14:51:20,566 : INFO : ConfigProcessor : Loading config from file C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\mpfconfig.yaml.
2025-03-28 14:51:20,577 : INFO : ConfigProcessor : Loading config: C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\mpfconfig.yaml
2025-03-28 14:51:20,577 : INFO : ConfigProcessor : Loading config from file C:\Users\homebrew\Desktop\thing_pinball\config\config.yaml.
2025-03-28 14:51:20,588 : INFO : ConfigProcessor : Loading config: C:\Users\homebrew\Desktop\thing_pinball\config\config.yaml
2025-03-28 14:51:20,589 : INFO : ConfigProcessor : Loading config: C:\Users\homebrew\Desktop\thing_pinball\config\service_mode.yaml
2025-03-28 14:51:20,591 : INFO : ConfigProcessor : Config file cache created: C:\Users\homebrew\AppData\Local\Temp\775282453bb9ae39cad69c39ab867a35.mpf_cache
2025-03-28 14:51:20,674 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\14eb6f99ffd433bf1b6bfef7e8b96202.mpf_cache
2025-03-28 14:51:20,675 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\8864efb2a88f9c685592172f4fd0a6a3.mpf_cache
2025-03-28 14:51:20,675 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\1352604168843921958881d1d8dd3c1b.mpf_cache
2025-03-28 14:51:20,676 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\14eb6f99ffd433bf1b6bfef7e8b96202.mpf_cache
2025-03-28 14:51:20,676 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\8864efb2a88f9c685592172f4fd0a6a3.mpf_cache
2025-03-28 14:51:20,677 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\82108c9d10735fbef5e8cced18b7d831.mpf_cache
2025-03-28 14:51:20,677 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\81d0f34cbd4c6d61cd4dad95e5100b6a.mpf_cache
2025-03-28 14:51:20,677 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\85b30d06c34a199299d858e267dca599.mpf_cache
2025-03-28 14:51:20,678 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\b6a0c3fa509e03dd7943cf1395b72ece.mpf_cache
2025-03-28 14:51:20,679 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\d18a920afddb781d4f34b36ac5cb2e09.mpf_cache
2025-03-28 14:51:20,679 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\50de7258194ae9293cbe8c4fce9577e7.mpf_cache
2025-03-28 14:51:20,680 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\2a76f107a833b8953199c5c910a26856.mpf_cache
2025-03-28 14:51:20,680 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\529fba7289b2d9f945cd5a4488c8b5fa.mpf_cache
2025-03-28 14:51:20,680 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\8c97cf9697840e2ca000923ba54f1b48.mpf_cache
2025-03-28 14:51:20,681 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\e8cb3f2c2e9a26851ec893c5156e3f7c.mpf_cache
2025-03-28 14:51:20,681 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\67cfb29d96313268f86362bebab46239.mpf_cache
2025-03-28 14:51:20,682 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2025-03-28 14:51:20,682 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-28-14-51-20-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': 'C:\\Users\\homebrew\\Desktop\\thing_pinball\\logs\\2025-03-28-14-51-20-mpf-mpf.log'}
2025-03-28 14:51:20,683 : INFO : Machine : MPF path: C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf
2025-03-28 14:51:20,683 : INFO : Machine : Machine path: C:\Users\homebrew\Desktop\thing_pinball
2025-03-28 14:51:20,683 : INFO : Machine : Platform: win32
2025-03-28 14:51:20,683 : INFO : Machine : Python executable location: C:\Users\homebrew\AppData\Local\Programs\Python\Python312\python.exe
2025-03-28 14:51:20,683 : INFO : Machine : Python version: 3.12.3 (64-bit)
2025-03-28 14:51:20,685 : INFO : Machine : Initializing MPF...
2025-03-28 14:51:20,895 : INFO : FAST [NET] : Trying to connect to com4 at 921600bps
2025-03-28 14:51:20,902 : INFO : FAST [NET] : Connected to com4 at 921600bps
2025-03-28 14:51:20,909 : INFO : FAST [NET] : Connected to FP-CPU-2000 with firmware v02.21
2025-03-28 14:51:20,940 : INFO : FAST [NET] : Registered I/O Board 0: Model: FP-I/O-0024, Firmware: 01.10, Switches: 24, Drivers: 8
2025-03-28 14:51:20,955 : INFO : FAST [NET] : Registered I/O Board 1: Model: FP-I/O-3208, Firmware: 01.10, Switches: 32, Drivers: 8
2025-03-28 14:51:20,971 : INFO : FAST [NET] : Registered I/O Board 2: Model: FP-I/O-0804, Firmware: 01.10, Switches: 8, Drivers: 4
2025-03-28 14:51:20,987 : INFO : FAST [NET] : Registered I/O Board 3: Model: FP-I/O-0804, Firmware: 01.10, Switches: 8, Drivers: 4
2025-03-28 14:51:20,988 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_dog_hunt_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_discovery_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_infected_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_blood_test_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_spider_head_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_wizard_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_ball_lock_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_game_mode_multiball_complete'====== Args={'value': 'False', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,014 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,015 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.3', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,143 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\homebrew\\Desktop\\thing_pinball\\logs\\2025-03-28-14-51-20-mpf-mpf.log', 'prev_value': None, 'change': True}
2025-03-28 14:51:21,144 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-03-28 14:51:21,181 : WARNING : ConfigValidator : Unrecognized config setting. "mode:discovery:timers:discovery_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,181 : WARNING : ConfigValidator : Unrecognized config setting. "mode:multiball:timers:multiball_jackpot_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,181 : WARNING : ConfigValidator : Unrecognized config setting. "mode:multiball:timers:right_ramp_validity_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,182 : WARNING : ConfigValidator : Unrecognized config setting. "mode:infected:timers:infected_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,182 : WARNING : ConfigValidator : Unrecognized config setting. "mode:base:timers:mode_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,182 : WARNING : ConfigValidator : Unrecognized config setting. "mode:wizard:timers:wizard_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,182 : WARNING : ConfigValidator : Unrecognized config setting. "mode:dog_hunt:timers:dog_hunt_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,183 : WARNING : ConfigValidator : Unrecognized config setting. "mode:blood_test:timers:blood_test_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,183 : WARNING : ConfigValidator : Unrecognized config setting. "mode:spider_head:timers:spider_head_timer:events_when_complete" is not a valid setting name.
2025-03-28 14:51:21,188 : INFO : EventManager : Event: ======'drop_target_bank_dog_bank_up'====== Args={}
2025-03-28 14:51:21,189 : INFO : EventManager : Event: ======'logicblock_spinner_value_updated'====== Args={'value': 0, 'enabled': False}
2025-03-28 14:51:21,189 : INFO : EventManager : Event: ======'logicblock_newton_hit_counter_updated'====== Args={'value': 0, 'enabled': False}
2025-03-28 14:51:23,546 : WARNING : Machine : Iterating device collections directly is deprecated and will be removed. Access by value(): device_collections[switches] -> device_collections['switches'].values()
2025-03-28 14:51:23,548 : INFO : SwitchController : <<<<<<< 's_trough_6' active >>>>>>>
2025-03-28 14:51:23,548 : INFO : SwitchController : <<<<<<< 's_trough_7' active >>>>>>>
2025-03-28 14:51:23,548 : INFO : SwitchController : <<<<<<< 's_trough_ball' active >>>>>>>
2025-03-28 14:51:23,548 : INFO : SwitchController : <<<<<<< 's_mode_opto' active >>>>>>>
2025-03-28 14:51:23,548 : INFO : SwitchController : <<<<<<< 's_newton_opto_made' active >>>>>>>
2025-03-28 14:51:23,549 : INFO : SwitchController : <<<<<<< 's_start_button' active >>>>>>>
2025-03-28 14:51:23,555 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (37, [FAST Platform Interface]) <switch.s_trough_6>
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (38, [FAST Platform Interface]) <switch.s_trough_7>
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (52, [FAST Platform Interface]) <switch.s_trough_ball>
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (64, [FAST Platform Interface]) <switch.s_mode_opto>
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (45, [FAST Platform Interface]) <switch.s_newton_opto_made>
2025-03-28 14:51:23,555 : INFO : SwitchController : Found active switch: (10, [FAST Platform Interface]) <switch.s_start_button>
2025-03-28 14:51:23,561 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,562 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,563 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,564 : WARNING : ConfigValidator : Unrecognized config setting. "slide_player:widgets" is not a valid setting name.
2025-03-28 14:51:23,566 : WARNING : YAML File Interface : YAML error found in file C:\Users\homebrew\Desktop\thing_pinball\data/high_scores.yaml. Line 2, Position 3: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
  in "C:\Users\homebrew\Desktop\thing_pinball\data/high_scores.yaml", line 2, column 3
2025-03-28 14:51:23,566 : WARNING : ConfigValidator : Unrecognized config setting. "high_score:events_when_complete" is not a valid setting name.
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score1_label'====== Args={'value': 'GRAND CHAMPION', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score1_name'====== Args={'value': 'THING', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score1_value'====== Args={'value': 5000000, 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score2_label'====== Args={'value': 'HIGH SCORE 1', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score2_name'====== Args={'value': 'MPF', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score2_value'====== Args={'value': 4000000, 'prev_value': None, 'change': True}
2025-03-28 14:51:23,566 : INFO : EventManager : Event: ======'machine_var_score3_label'====== Args={'value': 'HIGH SCORE 2', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score3_name'====== Args={'value': 'PINBALL', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score3_value'====== Args={'value': 3000000, 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score4_label'====== Args={'value': 'HIGH SCORE 3', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score4_name'====== Args={'value': 'WIZARD', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score4_value'====== Args={'value': 2000000, 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score5_label'====== Args={'value': 'HIGH SCORE 4', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score5_name'====== Args={'value': 'PLAYER', 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'machine_var_score5_value'====== Args={'value': 1000000, 'prev_value': None, 'change': True}
2025-03-28 14:51:23,567 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-03-28 14:51:23,569 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-03-28 14:51:29,805 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-03-28 14:51:29,807 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-03-28 14:51:29,958 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-95' coro=<BallDevice._initialize_async() done, defined at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_device.py:196> exception=ConfigFileError('Cannot use capacity and ball switches.')>
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_trough: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://missionpinball.org/logs)
2025-03-28 14:51:30,048 : INFO : ball_device.bd_shooter_lane : BCH: Initial count: 0
2025-03-28 14:51:30,049 : INFO : Machine : Starting the main run loop.
2025-03-28 14:51:30,049 : INFO : ball_device.bd_shooter_lane : State: idle
2025-03-28 14:51:30,049 : INFO : Machine : Shutting down...
2025-03-28 14:51:30,050 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-28 14:51:30,051 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-107' coro=<BallDevice._initialize_async() done, defined at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_device.py:196> exception=ConfigFileError("Ball device 'bd_ball_lock' uses switch 's_ball_lock_1' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch.")>
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 81, in __init__
    self.ball_device.raise_config_error(
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_ball_lock: Ball device 'bd_ball_lock' uses switch 's_ball_lock_1' which has a 'playfield_active' tag. This is handled internally by the device. Remove the redundant 'playfield_active' tag from that switch. Error Code: CFE-ball_device-13 (https://missionpinball.org/logs)
2025-03-28 14:51:30,072 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-03-28 14:51:30,074 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-03-28 14:51:30,075 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2025-03-28 14:51:30,119 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...p_bumper_3>')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...p_bumper_3>')>)>
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\driver.py", line 58, in _check_duplicate_coil_numbers
    raise AssertionError("Duplicate coil number {} for coil {}".format(coil.hw_driver.number, coil))
AssertionError: Duplicate coil number 19 for coil <coil.c_pop_bumper_3>
2025-03-28 14:51:31,182 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-116' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py:566> wait_for=<_OverlappedFuture cancelled>>
2025-03-28 14:51:31,185 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\devices\ball_device\switch_counter.py", line 90, in __init__
    self.ball_device.raise_config_error("Cannot use capacity and ball switches.", 3)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ball_device.bd_trough: Cannot use capacity and ball switches. Error Code: CFE-ball_device-3 (https://missionpinball.org/logs)
2025-03-28 14:51:31,187 : INFO : root : MPF run loop ended.
