2025-03-23 16:33:11,700 : INFO : root : Loading config.
2025-03-23 16:33:11,703 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-23 16:33:11,704 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\9c4fd671eedf0616c9c143d4588b87a8.mpf_cache
2025-03-23 16:33:11,792 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\b9f79c86485697d9eb62ba3cdcc388bf.mpf_cache
2025-03-23 16:33:11,793 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\3a13d33aed1669bafe3e56d7baff78a0.mpf_cache
2025-03-23 16:33:11,793 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\194daf2908cf002f5d26e5b3c0eabc95.mpf_cache
2025-03-23 16:33:11,794 : INFO : ConfigProcessor : Loading config from cache: C:\Users\homebrew\AppData\Local\Temp\b9f79c86485697d9eb62ba3cdcc388bf.mpf_cache
2025-03-23 16:33:11,795 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2025-03-23 16:33:11,795 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-03-23-16-33-11-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': 'C:\\Users\\homebrew\\Desktop\\fast_homebrew_godot\\logs\\2025-03-23-16-33-11-mpf-mpf.log'}
2025-03-23 16:33:11,795 : INFO : Machine : MPF path: C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf
2025-03-23 16:33:11,795 : INFO : Machine : Machine path: C:\Users\homebrew\Desktop\fast_homebrew_godot
2025-03-23 16:33:11,795 : INFO : Machine : Platform: win32
2025-03-23 16:33:11,795 : INFO : Machine : Python executable location: C:\Users\homebrew\AppData\Local\Programs\Python\Python312\python.exe
2025-03-23 16:33:11,795 : INFO : Machine : Python version: 3.12.3 (64-bit)
2025-03-23 16:33:11,797 : INFO : Machine : Initializing MPF...
2025-03-23 16:33:12,045 : INFO : FAST : Auto-detecting ports for the following connections: ['net']
2025-03-23 16:33:12,088 : INFO : FAST : Detected NET on port COM4
2025-03-23 16:33:12,203 : INFO : FAST [NET] : Trying to connect to COM4 at 921600bps
2025-03-23 16:33:12,211 : INFO : FAST [NET] : Connected to COM4 at 921600bps
2025-03-23 16:33:12,229 : INFO : FAST [NET] : Connected to FP-CPU-2000 with firmware v02.21
2025-03-23 16:33:12,260 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...FP-I/O-0804")>) at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...FP-I/O-0804")>) at C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 413, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 382, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 187, in _process_nn
    assert model == model_string_from_config, \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: I/O board config error. Board 0 is reporting as model FP-I/O-0024, but the config file says it's model FP-I/O-0804
2025-03-23 16:33:12,311 : INFO : Machine : Starting the main run loop.
2025-03-23 16:33:12,312 : INFO : Machine : Shutting down...
2025-03-23 16:33:12,312 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-03-23 16:33:13,414 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 413, in _socket_reader
    self.parse_incoming_raw_bytes(resp)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 373, in parse_incoming_raw_bytes
    self._dispatch_incoming_msg(msg)
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\base.py", line 382, in _dispatch_incoming_msg
    self.message_processors[msg_header](msg[3:])
  File "C:\Users\homebrew\AppData\Local\Programs\Python\Python312\Lib\site-packages\mpf\platforms\fast\communicators\net_neuron.py", line 187, in _process_nn
    assert model == model_string_from_config, \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: I/O board config error. Board 0 is reporting as model FP-I/O-0024, but the config file says it's model FP-I/O-0804
2025-03-23 16:33:13,419 : INFO : root : MPF run loop ended.
